apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: ppcluster
  region: us-west-2

managedNodeGroups:
  - name: worker1
    labels: {role: worker}
    instanceType: t3.small
    desiredCapacity: 1
    minSize: 1
    maxSize: 3
    iam:
      withAddonPolicies:
        albingress: true
    tags:
      nodegroup-role: worker