pipeline {
  agent any
  stages {
    stage('create eks cluster') {
      steps {
          withAWS(region:'us-west-2',credentials:'aws-static') {
            sh 'eksctl help'
          }
      }
    }

  }  
}